WebApplication1/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using WebApplication1.ActionFilters;
using WebApplication1.Utility;

namespace WebApplication1.Controllers
{
    public class CommentController : Controller
    {
        private readonly IWebHostEnvironment _host;
        private readonly ILogger<CommentController> _logger;
        private readonly ICommentService _comService;
        private readonly ISubmissionsService _subService;
        private readonly ITasksService _tService;
        public CommentController(IWebHostEnvironment host, ILogger<CommentController> logger, ICommentService comService, ISubmissionsService subService, ITasksService taskService)
        {
            _logger = logger;
            _host = host;
            _comService = comService;
            _subService = subService;
            _tService = taskService;
        }

        [HttpGet]
        [Authorize]
        [CommentsAuthorize]
        public IActionResult Create(string idEnc)
        {
            string idDec = Encryption.SymmetricDecrypt(idEnc);
            Guid id = Guid.Parse(idDec);

            //var sub = _subService.GetSubmission(id);
            //string email = User.Identity.Name;

            var comments = _comService.GetComments(id);
            ViewBag.Comments = comments;
            CommentViewModel myModel = new CommentViewModel();
            myModel.SubmissionId = idEnc;
            return View(myModel);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [CommentsAuthorize]
        public IActionResult Create(string idEnc, CommentViewModel data)
        {
            IPHostEntry ipEntry = Dns.GetHostEntry(Dns.GetHostName());
            IPAddress[] addr = ipEntry.AddressList;

            string idDec = Encryption.SymmetricDecrypt(idEnc);
            Guid id = Guid.Parse(idDec);

            data.Submission = _subService.GetSubmission(id);
            data.Email = User.Identity.Name;

            if (ModelState.IsValid){
                _comService.AddComment(data);
                _logger.LogInformation("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nComment was added successfully");
                TempData["feedback"] = "Comment was added successfully";
                ModelState.Clear();
            }else{
                _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nError while adding product to Database");
                TempData["warning"] = "Error while adding product to Database";
            }

            CommentViewModel myModel = new CommentViewModel();
            myModel.SubmissionId = idEnc;

            var comments = _comService.GetComments(id);
            ViewBag.Comments = comments;

            return View(myModel);
        }
    }
}

WebApplication1/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingCart.Application.Interfaces;
using ShoppingCart.Application.ViewModels;
using WebApplication1.Models;
using WebApplication1.Utility;
using WebApplication1.ActionFilters;

namespace WebApplication1.Controllers
{
    public class SubmissionController : Controller
    {
        private readonly ISubmissionsService _subService;
        private readonly IMembersService _memService;
        private readonly ITasksService _taskService;
        private readonly IWebHostEnvironment _host;
        private readonly ILogger<SubmissionController> _logger;

        public SubmissionController(ISubmissionsService subService, IMembersService memService, ITasksService taskService, IWebHostEnvironment host, ILogger<SubmissionController> logger)
        {
            _logger = logger;
            _host = host;
            _subService = subService;
            _taskService = taskService;
            _memService = memService;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "TEACHER")]
        public IActionResult TeacherSub(string id) {
            string idDec = Encryption.SymmetricDecrypt(id);
            Guid newGuid = Guid.Parse(idDec);
            var list = _subService.GetSubmissions(newGuid);
            return View(list);
        }


        [studentSubmissions]
        [Authorize(Roles = "STUDENT")]
        public IActionResult StudentSub()
        {
            string email = User.Identity.Name;
            var list = _subService.GetSubmissions(email);
            return View(list);
        }


        [Authorize]
        public IActionResult Download(string idEnc)
        {

            string idDec = Encryption.SymmetricDecrypt(idEnc);
            Guid id = Guid.Parse(idDec);

            IPHostEntry ipEntry = Dns.GetHostEntry(Dns.GetHostName());
            IPAddress[] addr = ipEntry.AddressList;

            var sub = _subService.GetSubmission(id);
            string absolutePath = @"ValuableFiles\" + sub.File;

            FileStream fs = new FileStream(absolutePath, FileMode.Open, FileAccess.Read);
            MemoryStream toDownload = new MemoryStream();
            fs.CopyTo(toDownload);
            string email = sub.Email;
            var member = _memService.GetMember(email);

            bool pass = Encryption.VerifyData(toDownload, member.PublicKey, sub.Signature);
            MemoryStream actualFile = Encryption.HybridDecrypt(toDownload, member.PrivateKey);
            

            if (pass == true)
            {
                _logger.LogInformation("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nPDF downloaded");
                return File(actualFile, "application/octet-stream", Guid.NewGuid() + ".pdf");
            }
            else {
                _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nSomething went wrong");
                ModelState.AddModelError("", "Something went wrong");
                return View();
            }
        }

        [HttpGet]
        [Authorize]
        public IActionResult Upload(string idEnc)
        {
            SubmissionViewModel myModel = new SubmissionViewModel();
            myModel.TaskId = idEnc;
            return View(myModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Upload(IFormFile file, SubmissionViewModel data, string idEnc)
        {
            string idDec = Encryption.SymmetricDecrypt(idEnc);
            Guid id = Guid.Parse(idDec);

            SubmissionViewModel myModel = new SubmissionViewModel();
            myModel.TaskId = idEnc;

            data.Task = _taskService.GetTask(id);
            data.Email = User.Identity.Name;
            
            var member = _memService.GetMember(data.Email);

            IPHostEntry ipEntry = Dns.GetHostEntry(Dns.GetHostName());
            IPAddress[] addr = ipEntry.AddressList;

            if (data.Task.Deadline > DateTime.Now)
            {
                if (ModelState.IsValid)
                {
                    if (file != null)
                    {

                        string uniqueFilename;
                        if (System.IO.Path.GetExtension(file.FileName) == ".pdf" && file.Length < 1048576)
                        {
                            //137 80 78 71 13 10 26 10
                            byte[] whiteList = new byte[] { 37, 80, 68, 70 };
                            if (file != null)
                            {
                                MemoryStream userFile = new MemoryStream();
                                using (var f = file.OpenReadStream())
                                {

                                    byte[] buffer = new byte[4];
                                    f.Read(buffer, 0, 4);

                                    for (int i = 0; i < whiteList.Length; i++)
                                    {
                                        if (whiteList[i] == buffer[i])
                                        { }
                                        else
                                        {
                                            _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nFile is not valid and accapteable");
                                            ModelState.AddModelError("file", "file is not valid and accapteable");
                                            return View();
                                        }
                                    }

                                    f.Position = 0;

                                    //uploading the file
                                    uniqueFilename = Guid.NewGuid() + Path.GetExtension(file.FileName);
                                    data.File = uniqueFilename;

                                    string absolutePath = @"ValuableFiles\" + uniqueFilename;
                                    try
                                    {
                                        file.CopyTo(userFile);
                                        var encryptedFileMemoryStream = Encryption.HybridEncrypt(userFile, member.PublicKey);
                                        System.IO.File.WriteAllBytes(absolutePath, encryptedFileMemoryStream.ToArray());
                                        data.Signature = Encryption.SignData(encryptedFileMemoryStream, member.PrivateKey);
                                        f.Close();
                                    }
                                    catch (Exception e)
                                    {
                                        _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nError happend while saving file.");
                                        return View("Error", new ErrorViewModel() { Message = "Error while saving the file. Try again later" });
                                    }
                                }
                            }
                            _subService.AddSubmission(data);
                            _logger.LogInformation("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nAssignment submitted successfully.");
                            TempData["message"] = "Assignment submitted successfully";
                            return View(myModel);
                        }
                        else
                        {
                            _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nFile is not valid and acceptable or size is greater than 10Mb");
                            ModelState.AddModelError("", "File is not valid and acceptable or size is greater than 10Mb");
                            return View(myModel);
                        }
                    }
                    else {
                        _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nNo file was selected");
                        ModelState.AddModelError("", "No file was selected");
                        return View(myModel);
                    }
                }
                else
                {
                    _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nOperation failed due to input error.");
                    ModelState.AddModelError("", "Check your input. Operation failed");
                    return View(myModel);
                }
            }
            else {
                _logger.LogError("IP: " + addr[1].ToString() + "\nTime: " + DateTime.Now + "\nUser: " + User.Identity.Name + "\nDeadline expired");
                ModelState.AddModelError("", "Sorry, deadline has been expired.");
                return View(myModel);
            }
        }
    }
}

WebApplication1/Views/Submission/Create.cshtml
@model ShoppingCart.Application.ViewModels.SubmissionViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SubmissionViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input type="file" name="File" class="form-control" />
                <span name="file" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/Submission/StudentSub.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.SubmissionViewModel>

@{
    ViewData["Title"] = "StudentSub";
}

<h1>Your Submissions</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.File)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.File)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Comments", "Create", "Comment", new { idEnc = WebApplication1.Utility.Encryption.SymmetricEncrypt(item.Id.ToString()) }) |
                @Html.ActionLink("Download File", "Download", "Submission", new { idEnc = WebApplication1.Utility.Encryption.SymmetricEncrypt(item.Id.ToString()) })
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication1/Views/Submission/TeacherSub.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.SubmissionViewModel>

@{
    ViewData["Title"] = "TeacherSub";
}

@{
    List<string> list = new List<string>();

    foreach (var item in Model)
    {
        list.Add(item.Signature);
    }

    var query = list.GroupBy(x => x)
              .Where(g => g.Count() > 1)
              .Select(y => y.Key)
              .ToList();

}

    <h1>TeacherSub</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.File)
                </th>
                <th>
                    @Html.DisplayName("Flag")
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.File)
                </td>
                <td>
                    @{
                        if (query.Contains(item.Signature)){
                            <p>COPIED</p>
                        }
                        else
                        {
                            <p>NOT</p>
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("Comments", "Create", "Comment", new { idEnc = WebApplication1.Utility.Encryption.SymmetricEncrypt(item.Id.ToString()) }) |
                    @Html.ActionLink("Download File", "Download", "Submission", new { idEnc = WebApplication1.Utility.Encryption.SymmetricEncrypt(item.Id.ToString()) })
                </td>
            </tr>
            }
        </tbody>
    </table>

WebApplication1/Views/Submission/Upload.cshtml
@model ShoppingCart.Application.ViewModels.SubmissionViewModel

@{
    ViewData["Title"] = "Upload";
}

<h1>Upload</h1>

<h4>SubmissionViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Upload" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <input type="hidden" name="idEnc" value="@Model.TaskId" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input type="file" name="File" class="form-control" />
                <span name="file" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}